{% set version = "8.9.2.26" %}
{% set cuda_version = cudatoolkit | replace('.*',"") %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set arch = "ppc64le" %}  # [ppc64le]
{% set arch = "x86_64" %}  # [x86_64]
  
package:
  name: cudnn
  version: {{ version.rsplit('.', 1)[0] + "_" + cuda_version }}

build:
  number: 1
  missing_dso_whitelist:
          - "*/libstdc++.so.6"      
          - "*/libm.so.6"      
          - "*/librt.so.1"      
          - "*/libpthread.so.0"      
          - "*/libdl.so.2"      
          - "*/libgcc_s.so.1"      
          - "*/libc.so.6"      
          - "*/ld*64.so.2"    

requirements:
  run:
    - cudatoolkit {{ cudatoolkit }}

source:
  url: https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/linux-{{ arch }}/cudnn-linux-{{ arch }}-{{ version }}_cuda{{ cuda_major }}-archive.tar.xz
  sha256: ccafd7d15c2bf26187d52d79d9ccf95104f4199980f5075a7c1ee3347948ce32  # [x86_64 and cuda_major == '12']
  sha256: 39883d1bcab4bd2bf3dac5a2172b38533c1e777e45e35813100059e5091406f6  # [x86_64 and cuda_major == '11']
  sha256: 4f5e5bd01570c4805b93fb199f8bb6f8475d016948c55abf48fed9ffe89d13e5  # [ppc64le and cuda_major == '12']
  sha256: cc3267d7a6016949fa62a8f48184a7316a4798f0c192809c8184e441778fe0ce  # [ppc64le and cuda_major == '11'] 
  folder: cudnn

test:
  commands:
    - test -f ${PREFIX}/lib/libcudnn.so

about: 
    license_file: LICENSE
    summary: The NVIDIA CUDA Deep Neural Network library. A GPU-accelerated library of primitives for deep neural networks.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
