{% set version = "8.9.6.50" %}
{% set cuda_version = cudatoolkit | replace('.*',"") %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set arch = "ppc64le" %}  # [ppc64le]
{% set arch = "x86_64" %}  # [x86_64]
  
package:
  name: cudnn
  version: {{ version.rsplit('.', 1)[0] + "_" + cuda_version }}

build:
  number: 1
  missing_dso_whitelist:
          - "*/libstdc++.so.6"      
          - "*/libm.so.6"      
          - "*/librt.so.1"      
          - "*/libpthread.so.0"      
          - "*/libdl.so.2"      
          - "*/libgcc_s.so.1"      
          - "*/libc.so.6"      
          - "*/ld*64.so.2"    

requirements:
  run:
    - cudatoolkit {{ cudatoolkit }}

source:
  url: https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/linux-{{ arch }}/cudnn-linux-{{ arch }}-{{ version }}_cuda{{ cuda_major }}-archive.tar.xz
  sha256: 1722259db95265bb3813438a5a1c6ecd979de89ae4536603904042e124d302d5  # [x86_64 and cuda_major == '12']
  sha256: a0e2ef55e99f4cd647f7d1daaa5aa4504ffa335ba30186d5c3288f2f47df057e  # [x86_64 and cuda_major == '11']
  sha256: 2023fccc93226b7ef285a75f02c2c1f0704b7309c15c4b6333a56de896d06852  # [ppc64le and cuda_major == '12']
  sha256: 8b6590fea7e194879d74b0feae9dddcec933900794c126a8cdc55acec338e336  # [ppc64le and cuda_major == '11']
  folder: cudnn

test:
  commands:
    - test -f ${PREFIX}/lib/libcudnn.so

about: 
    license_file: LICENSE
    summary: The NVIDIA CUDA Deep Neural Network library. A GPU-accelerated library of primitives for deep neural networks.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
