{% set version = "8.3.0.98" %}
{% set cuda_version = cudatoolkit | replace('.*',"") %}

{% set arch = "ppc64le" %}  # [ppc64le]
{% set arch = "x64" %}  # [x86_64]
  
package:
  name: cudnn
  version: {{ version.rsplit('.', 1)[0] + "_" + cuda_version }}

build:
  number: 1
  missing_dso_whitelist:
          - "*/libstdc++.so.6"      
          - "*/libm.so.6"      
          - "*/librt.so.1"      
          - "*/libpthread.so.0"      
          - "*/libdl.so.2"      
          - "*/libgcc_s.so.1"      
          - "*/libc.so.6"      
          - "*/ld*64.so.2"    

requirements:
  run:
    - cudatoolkit {{ cudatoolkit }}

source:
  url: https://developer.download.nvidia.com/compute/redist/cudnn/v{{ ".".join(version.split(".")[:3]) }}/cudnn-11.5-linux-{{ arch }}-v{{ version }}.tgz
  sha256: 44c6f5ad5cb12fb74fa0c9a1e7caaf4f04d755adf11a2e5b6c9e417da376b2b2  # [x86_64]
  sha256: c3fd57c06f625139edd3788493925089ad8148599bffc22f6f9948370e5850ee  # [ppc64le]
  folder: cudnn

test:
  commands:
    - test -f ${PREFIX}/lib/libcudnn.so

about: 
    license_file: LICENSE
    summary: The NVIDIA CUDA Deep Neural Network library. A GPU-accelerated library of primitives for deep neural networks.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
