{% set version = "8.1.0.77" %}
{% set cuda_version = cudatoolkit | replace('.*',"") %}
{% set cuda_major_version = ".".join(cuda_version.split("."))[:2] %}

{% set cudnn_version = "8.1.0.77-1" %}
{% set arch = "ppc64le" %}  # [ppc64le]
{% set arch = "x86_64" %}  # [x86_64]
  
package:
  name: cudnn
  version: {{ cudnn_version.rsplit('.', 1)[0] + "_" + cuda_version }}

build:
  number: 1
  missing_dso_whitelist:
          - "*/libstdc++.so.6"      
          - "*/libm.so.6"      
          - "*/librt.so.1"      
          - "*/libpthread.so.0"      
          - "*/libdl.so.2"      
          - "*/libgcc_s.so.1"      
          - "*/libc.so.6"      
          - "*/ld*64.so.2"    

requirements:
  run:
    - cudatoolkit {{ cudatoolkit }}

source:
  url: https://developer.download.nvidia.com/compute/redist/cudnn/v{{ ".".join(version.split(".")[:3]) }}/cudnn-{{ cuda_version }}-linux-x64-v{{ version }}.tgz  # [linux64]
  url: https://developer.download.nvidia.com/compute/redist/cudnn/v{{ ".".join(version.split(".")[:3]) }}/cudnn-{{ cuda_version }}-linux-ppc64le-v{{ version }}.tgz  # [ppc64le]
  url: https://developer.download.nvidia.com/compute/redist/cudnn/v{{ ".".join(version.split(".")[:3]) }}/cudnn-{{ cuda_version }}-windows10-x64-v{{ version }}.zip  # [win and cuda_version == "10.2"]
  url: https://developer.download.nvidia.com/compute/redist/cudnn/v{{ ".".join(version.split(".")[:3]) }}/cudnn-{{ cuda_version }}-windows-x64-v{{ version }}.zip  # [win and cuda_version == "11.2"]
  sha256: 508a7aaad4e9a167b63cc063018541c74e089a1f548715832c50249dc2098dfa  # [win64 and cuda_version == "10.2"]
  sha256: f5a23402ebed5b2add2ae0dc79df42f055f5851bbb3b1d0f6aa9dcdeeb9346ce  # [win64 and cuda_version == "11.2"]
  sha256: c5bc617d89198b0fbe485156446be15a08aee37f7aff41c797b120912f2b14b4  # [linux64 and cuda_version == "10.2"]
  sha256: dbe82faf071d91ba9bcf00480146ad33f462482dfee56caf4479c1b8dabe3ecb  # [linux64 and cuda_version == "11.2"]
  folder: cudnn

test:
  commands:
#    - test -f $PREFIX/include/cudnn.h                  # [linux]
#    - test -f $PREFIX/include/cudnn_adv_train.h        # [linux]
#    - test -f $PREFIX/lib/libcudnn.so                  # [linux]
#    - test -f $PREFIX/lib/libcudnn_adv_train.so        # [linux]
    - test -f ${PREFIX}/lib/libcudnn.so
    - test -f ${PREFIX}/lib/libcudnn_static.a

about: 
    license_file: LICENSE
    summary: The NVIDIA CUDA Deep Neural Network library. A GPU-accelerated library of primitives for deep neural networks.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
